sudo: false

language: python

services:
  - docker

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - docker pull opendxl/opendxl-broker
  - docker run -d -p 127.0.0.1:8883:8883 -p 127.0.0.1:8443:8443 opendxl/opendxl-broker
  - docker ps -a

install:
  - pip install .[test]

before_script:
  - python -m dxlclient provisionconfig dxlclient/test 127.0.0.1 client -u admin -p password
  - cp dxlclient/test/dxlclient.config dxlclient/test/client_config.cfg
  - sed -i -e "s/127.0.0.1;127.0.0.1/127.0.0.1/g" -e "/local/d" -e "/docker/d" dxlclient/test/client_config.cfg
  - cat dxlclient/test/client_config.cfg

script:
  - python setup.py ci
